[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd apps/chat && npm install"]

[phases.build]
cmds = ["cd apps/chat && npm run build"]

[start]
cmd = "cd apps/chat && npm start"
