# Простая конфигурация для monorepo
[variables]
  NODE_ENV = "production"

[phases.install]
cmds = [
  "npm ci",
  "cd apps/chat && npm ci"
]

[phases.build]
cmds = [
  "cd apps/chat && npm run build"
]

[start]
cmd = "cd apps/chat && npm start"
